apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "echo-app.fullname" . }}
  labels:
    {{- include "echo-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "echo-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "echo-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: echo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
