apiVersion: v1
kind: Service
metadata:
  name: {{ include "echo-app.fullname" . }}
  labels:
    {{- include "echo-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "echo-app.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
